name: ProSolNet
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - biopython==1.86
      - certifi==2025.11.12
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - mdtraj==1.10.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - netcdf4==1.7.3
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pyg-lib==0.5.0+pt26cu126
      - pyparsing==3.2.5
      - pyrosetta==2024.39+release.59628fb
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - scipy==1.15.3
      - sentencepiece==0.2.1
      - six==1.17.0
      - sympy==1.13.1
      - tokenizers==0.22.1
      - torch==2.6.0+cu126
      - torch-cluster==1.6.3+pt26cu126
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt26cu126
      - torch-sparse==0.6.18+pt26cu126
      - torch-spline-conv==1.2.2+pt26cu126
      - torchaudio==2.6.0+cu126
      - torchvision==0.21.0+cu126
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/wzc/anaconda3/envs/ProSolNet
